const products = [
  {
    id: 1,
    type: "Mushroom",
    img: "./img/MenuSection/Image01.png",
    name: "Italian",
    text: "Filling: onion, potato, tomato, mushrooms, cheese, olives, meat...",
    buttonSize1: "22",
    buttonSize2: "28",
    buttonSize3: "33",
    buttonIngridients: "+ Ingridients",
    price: 8.35,
    buttonMinus: "-",
    quantity: 1,
    buttonPlus: "+",
  },
  {
    id: 2,
    type: "Meat",
    img: "./img/MenuSection/Image02.png",
    name: "Venecia",
    text: "Filling: onion, potato, tomato, mushrooms, cheese, olives, meat...",
    buttonSize1: "22",
    buttonSize2: "28",
    buttonSize3: "33",
    buttonIngridients: "+ Ingridients",
    price: 7.35,
    buttonMinus: "-",
    quantity: 1,
    buttonPlus: "+",
  },
  {
    id: 3,
    type: "Meat",
    img: "./img/MenuSection/Image03.png",
    name: "Meat",
    text: "Filling: onion, potato, tomato, mushrooms, cheese, olives, meat...",
    buttonSize1: "22",
    buttonSize2: "28",
    buttonSize3: "33",
    buttonIngridients: "+ Ingridients",
    price: 9.35,
    buttonMinus: "-",
    quantity: 1,
    buttonPlus: "+",
  },
  {
    id: 4,
    type: "Vegetarian",
    img: "./img/MenuSection/Image04.png",
    name: "Cheese",
    text: "Filling: onion, potato, tomato, mushrooms, cheese, olives, meat...",
    buttonSize1: "22",
    buttonSize2: "28",
    buttonSize3: "33",
    buttonIngridients: "+ Ingridients",
    price: 8.35,
    buttonMinus: "-",
    quantity: 1,
    buttonPlus: "+",
  },
  {
    id: 5,
    type: "SeaProducts",
    img: "./img/MenuSection/Image05.png",
    name: "Argentina",
    text: "Filling: onion, potato, tomato, mushrooms, cheese, olives, meat...",
    buttonSize1: "22",
    buttonSize2: "28",
    buttonSize3: "33",
    buttonIngridients: "+ Ingridients",
    price: 7.35,
    buttonMinus: "-",
    quantity: 1,
    buttonPlus: "+",
  },
  {
    id: 6,
    type: "Mushroom",
    img: "./img/MenuSection/Image06.png",
    name: "Gribnaya",
    text: "Filling: onion, potato, tomato, mushrooms, cheese, olives, meat...",
    buttonSize1: "22",
    buttonSize2: "28",
    buttonSize3: "33",
    buttonIngridients: "+ Ingridients",
    price: 6.35,
    buttonMinus: "-",
    quantity: 1,
    buttonPlus: "+",
  },
  {
    id: 7,
    type: "Mushroom",
    img: "./img/MenuSection/Image07.png",
    name: "Tomato",
    text: "Filling: onion, potato, tomato, mushrooms, cheese, olives, meat...",
    buttonSize1: "22",
    buttonSize2: "28",
    buttonSize3: "33",
    buttonIngridients: "+ Ingridients",
    price: 7.35,
    buttonMinus: "-",
    quantity: 1,
    buttonPlus: "+",
  },
  {
    id: 8,
    type: "Vegetarian",
    img: "./img/MenuSection/Image08.png",
    name: "Italian x2",
    text: "Filling: onion, potato, tomato, mushrooms, cheese, olives, meat...",
    buttonSize1: "22",
    buttonSize2: "28",
    buttonSize3: "33",
    buttonIngridients: "+ Ingridients",
    price: 8.35,
    buttonMinus: "-",
    quantity: 1,
    buttonPlus: "+",
  },
];

export default products;
